# Generated by Django 4.0.8 on 2023-01-05 18:44

import uuid

import django.contrib.postgres.fields
import notice.models
from default_data.services import insert_default_type_events
from django.db import migrations, models
from notice.beats import create_default_beats


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('create schema if not exists content;'),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, verbose_name='Name')),
                ('subject', models.TextField(max_length=512, verbose_name='Subject')),
                ('template_file', models.FileField(upload_to='emails_template/', validators=[notice.models.validate_file_contents])),
                ('template_params', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Type_event',
                'verbose_name_plural': 'Type_event',
                'db_table': 'content"."type_event',
            },
        ),
        migrations.AddIndex(
            model_name='typeevent',
            index=models.Index(fields=['name'], name='type_event_name_0b64a5_idx'),
        ),
        migrations.RunPython(insert_default_type_events),
        migrations.RunPython(create_default_beats),
    ]
