# Generated by Django 4.0.8 on 2023-01-12 12:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import notice.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateManualMailing',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, verbose_name='Name')),
                ('date_to_send', models.DateField(validators=[notice.models.validate_date_to_send])),
            ],
            options={
                'verbose_name': 'Create manual mailing',
                'verbose_name_plural': 'Create manual mailings',
                'db_table': 'content"."create_manual_mailing',
            },
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, verbose_name='Name')),
                ('subject', models.TextField(max_length=512, verbose_name='Subject')),
                ('template_file', models.FileField(upload_to='emails_template/', validators=[notice.models.validate_file_contents])),
                ('template_params', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Type event',
                'verbose_name_plural': 'Type events',
                'db_table': 'content"."type_event',
            },
        ),
        migrations.AddIndex(
            model_name='typeevent',
            index=models.Index(fields=['name'], name='type_event_name_0b64a5_idx'),
        ),
        migrations.AddField(
            model_name='createmanualmailing',
            name='type_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.typeevent', verbose_name='Type event (template)'),
        ),
        migrations.AddIndex(
            model_name='createmanualmailing',
            index=models.Index(fields=['name'], name='create_manu_name_09da8b_idx'),
        ),
    ]
