# Generated by Django 4.0.8 on 2023-01-05 18:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeevent', options={'verbose_name': 'Type event', 'verbose_name_plural': 'Type events'},
        ),
        migrations.CreateModel(
            name='CreateManualMailing',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, verbose_name='Name')),
                ('date_to_send', models.DateField()),
                (
                    'type_event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='notice.typeevent', verbose_name='Template'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Create manual mailing',
                'verbose_name_plural': 'Create manual mailings',
                'db_table': 'content"."create_manual_mailing',
            },
        ),
        migrations.AddIndex(
            model_name='createmanualmailing', index=models.Index(fields=['name'], name='create_manu_name_09da8b_idx'),
        ),
    ]
