# Generated by Django 4.0.8 on 2023-01-02 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeevent',
            name='template_params',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None
            ),
        ),
    ]
