# Generated by Django 4.0.8 on 2023-01-05 18:55

from default_data.services import insert_default_type_events
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_default_type_events),
    ]
