# Generated by Django 4.0.8 on 2023-01-03 18:12

import notice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_typeevent_template_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeevent',
            name='template_file',
            field=models.FileField(upload_to='emails_template/', validators=[notice.models.validate_file_contents]),
        ),
    ]
