# Generated by Django 4.0.8 on 2023-01-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20230105_1855'),
        ('notice', '0003_alter_typeevent_template_file'),
    ]

    operations = []
