# Generated by Django 4.0.8 on 2023-01-12 05:20

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_merge_20230111_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmanualmailing',
            name='date_to_send',
            field=models.DateField(validators=[notice.models.validate_date_to_send]),
        ),
        migrations.AlterField(
            model_name='createmanualmailing',
            name='type_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.typeevent', verbose_name='Type event (template)'),
        ),
    ]
