# Generated by Django 4.0.8 on 2023-01-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_createmanualmailing_date_to_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmanualmailing',
            name='users_filter',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='UsersFilter'),
        ),
    ]
